### ISSUE TITLE
First level of comment is no different to child ones

### ISSUE THREAD

**Issue by Majki** [unzan/TerribleName#12]
Picture will explain
![zaznaczenie_497](https://cloud.githubusercontent.com/assets/1552256/6020696/4bc7e3e0-abaf-11e4-8ea6-68da736d50a4.png)

Would be cool to get rid of line I highlighted with yellow. It will make easier making distinction between "main comment" and "childs".

**Comment by unzan** [comment]
You're right. It's nicer that way.
