### ISSUE TITLE
RES Never Ending feature: Dark Theme, few elements still white

### ISSUE THREAD

**Issue by Scellow** [unzan/TerribleName#13]
I wanted to make a pull request but i have no idea what file to change, i'm a CSS newbie sorry!

FIX:

    .NERPageMarker { background-color : #242a32; border-color : #111417; }
    #progressIndicator { background-color : #242a32; border-color : #111417; }

**Comment by unzan** [comment]
It's still white because I don't use RES Never Ending. Fixed in 1842ab43db84855aa3c1ff8791c0b0858c9c74a2 and Dark Variant theme in userstyles.org has been updated too. Thanks.
